# Generated by Django 4.2.4 on 2023-09-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vakansiyalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malumot', models.CharField(max_length=200, verbose_name='Ish haqida malumot...')),
                ('ismi', models.CharField(max_length=200, verbose_name='Ish beruvchining ismi:')),
                ('narx', models.CharField(max_length=100, verbose_name='Taklif qilinayotgan narx:')),
                ('image', models.ImageField(default='static/img/team-1.jpg', upload_to='maruzaimg/', verbose_name='Rasm')),
            ],
            options={
                'verbose_name': 'Vakansiya',
                'verbose_name_plural': 'Vakansiyalarlar',
            },
        ),
    ]
