# Generated by Django 4.2.4 on 2023-09-01 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Darslar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='', verbose_name='Videoni joylashtring:')),
                ('popular', models.IntegerField(default=0, verbose_name="Ko'rilganlar soni")),
                ('image', models.ImageField(upload_to='maruzaimg/', verbose_name='Video yuzi uchun rasm:')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(max_length=150, verbose_name='Slug Masalan: "1-dars" (bo\'shliqsiz yozilishi shart)')),
            ],
            options={
                'verbose_name': 'Maruza',
                'verbose_name_plural': 'Maruzalar',
            },
        ),
        migrations.CreateModel(
            name='FoydaliHavolalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sayt_nomi', models.CharField(max_length=200, verbose_name='Sayt nomi:')),
                ('malumoti', models.CharField(max_length=100, verbose_name='Ozgina malumot:')),
                ('url', models.URLField(verbose_name='Sayt linki:')),
            ],
            options={
                'verbose_name': 'Istedod',
                'verbose_name_plural': 'Istedodlilar',
            },
        ),
        migrations.CreateModel(
            name='Istedodlilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='static/img/team-1.jpg', upload_to='maruzaimg/', verbose_name='Rasm:')),
                ('ismi', models.CharField(max_length=200, verbose_name='Ismi:')),
                ('narx', models.CharField(max_length=100, verbose_name='Ism Familiyasi:')),
            ],
            options={
                'verbose_name': 'Istedod',
                'verbose_name_plural': 'Istedodlilar',
            },
        ),
        migrations.AlterModelOptions(
            name='vakansiyalar',
            options={'verbose_name': 'Vakansiya', 'verbose_name_plural': 'Vakansiyalar'},
        ),
        migrations.AlterField(
            model_name='vakansiyalar',
            name='image',
            field=models.ImageField(default='static/img/team-1.jpg', upload_to='maruzaimg/', verbose_name='Rasm:'),
        ),
    ]
