# Generated by Django 4.2.4 on 2023-09-01 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha', '0002_darslar_foydalihavolalar_istedodlilar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='darslar',
            options={'verbose_name': 'Dars', 'verbose_name_plural': 'Darslar'},
        ),
    ]
