# Generated by Django 4.2.4 on 2023-09-02 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha', '0003_alter_darslar_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foydalihavolalar',
            options={'verbose_name': 'Foydali havola', 'verbose_name_plural': 'Foydali havolalar'},
        ),
    ]
