# Generated by Django 4.2.4 on 2023-09-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha', '0004_alter_foydalihavolalar_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darslar',
            name='date',
            field=models.CharField(max_length=150, verbose_name='Video muallifi:'),
        ),
    ]
